version: "3.9"

services:
  db:
    image: postgres:18.3-alpine3.23
    container_name: anime_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: loveyouforever
      POSTGRES_DB: anime_db
    ports:
      - "5432:5432"
  
  backend:
    build: ./backend
    container_name: anime_api
    environment:
      DATABASE_URL: postgres://admin:loveyouforever@db:5432/anime_db
    ports:
      - "8080:8080"
    depends_on:
      - db